version: '3.7'

services:
  backend:
    build:
      context: ./backend
    image: springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/your_mongo_db

    depends_on:
      - mongo
    networks:
      - mynetwork
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db
  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Ścieżka do pliku konfiguracyjnego NGINX
      - ./frontend:/usr/share/nginx/html  # Ścieżka do katalogu z plikami frontendowymi
    ports:
      - "80:80"
    depends_on:
      - backend  # NGINX zależy od backendu (Spring Boot)
    networks:
      - mynetwork
# Definiowanie sieci
networks:
  mynetwork:
    driver: bridge

# Definiowanie wolumenów (dla przechowywania danych bazy danych)
volumes:
  mongo-data:
