version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    image: springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - mynetwork
    restart: always 

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017" 
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db 
    restart: always 
  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge 

volumes:
  mongo-data: 
