version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    image: springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - mynetwork
    restart: always 

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017" 

    environment:
      - MONGO_INITDB_DATABASE=mydb

    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db 
    restart: always 

  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80" 
    depends_on:
      - backend 
    networks:
      - mynetwork
    restart: always 

networks:
  mynetwork:
    driver: bridge 

volumes:
  mongo-data: 
