version: '3.7'

services:
  # Usługa backendowa (Spring Boot)
  backend:
    build:
      context: ./backend
    image: springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdb
      - SPRING_DATASOURCE_USERNAME=albert
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - mynetwork

  # Usługa bazy danych (PostgreSQL)
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=albert
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yourdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Ścieżka do pliku konfiguracyjnego NGINX
      - ./frontend:/usr/share/nginx/html  # Ścieżka do katalogu z plikami frontendowymi
    ports:
      - "80:80"
    depends_on:
      - backend  # NGINX zależy od backendu (Spring Boot)
    networks:
      - mynetwork
# Definiowanie sieci
networks:
  mynetwork:
    driver: bridge

# Definiowanie wolumenów (dla przechowywania danych bazy danych)
volumes:
  postgres-data:
